Update finish

diff --git a/root/etc/s6-overlay/s6-rc.d/slinger/finish b/root/etc/s6-overlay/s6-rc.d/slinger/finish
--- a/root/etc/s6-overlay/s6-rc.d/slinger/finish
+++ b/root/etc/s6-overlay/s6-rc.d/slinger/finish
@@ -1,6 +1,6 @@
 #!/usr/bin/with-contenv bash
 
-echo "=== Starting aircast finish ==="
+echo "=== Starting slinger finish ==="
 
 if [ "$ARCH_VAR" == "amd64" ]; then
   ARCH_VAR=linux-x86_64
@@ -14,10 +14,10 @@ echo " ARCH_VAR=${ARCH_VAR}"
 ARCH_VAR="${ARCH_VAR}-static"
 
 echo " /bin/aircast-${ARCH_VAR}"
-if [ ! -f /bin/aircast-${ARCH_VAR} ]; then
-    echo " /bin/aircast-${ARCH_VAR} executable not found - exit 125 to prevent restart"
+if [ ! -f ${var_path}/${SLINGER_VAR} ]; then
+    echo " ${var_path}/${SLINGER_VAR} configuration file not found - exit 125 to prevent restart"
     echo "=== Exiting aircast finish - 125 ==="
     exit 125
 fi
 
-echo "=== Exiting aircast finish ==="
+echo "=== Exiting slinger finish ==="
